### ISSUE TITLE
Bulleted Lists

### ISSUE THREAD

**Issue by vijayb24** [singerla/pptx-automizer#101]
how to add bulleted lists  instead of blank texts

**Comment by singerla** [comment]
First, you need apply your desired bullet point format to first line.

Then, try this:
```ts
// Use EOL or this simple line break
const text = ["first line", "second line"].join(`
`);

// inside slide modification:
// modify.setText(text);
```

**Comment by vijayb24** [comment]
Thanks for the reply, can I also add the bullets as tag value and replaceText with textreplacements instead of shapes?

**Comment by singerla** [comment]
Interesting question! :) It works, please see [replace-tagged-text.test.ts](https://github.com/singerla/pptx-automizer/blob/main/__tests__/replace-tagged-text.test.ts)

**Comment by vijayb24** [comment]
Thanks. will try it out.
