### ISSUE TITLE
[Help Needed] Can't copy slideMasters with themeOverride

### ISSUE THREAD

**Issue by androidsoft** [singerla/pptx-automizer#104]
Hello!

I have an issue with relations when proceed to copy slideMasters:
```
TypeError: Cannot read properties of undefined (reading 'filenameBase')
    at Chart.<anonymous> (/Users/user/Documents/pptx-automizer-main/src/shapes/chart.ts:235:31)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/user/Documents/pptx-automizer-main/src/shapes/chart.ts:5:58)
```

I've tried connect XmlRelationshipHelper, then go to research deeper and this led me to the point where there is currently no way to handle the so-called "themeOverride" rels.

The thing is, when we override the standard theme colors in PowerPoint with custom ones, a themeOverrideN.xml is created in the /ppt/theme path, which can then be applied in charts to apply custom chart colors on top of the standard theme colors. After that, a link to the themeOverride is created in the chart's relations (see example in ppt/charts/_rels/chart2.xml.rels). Unfortunately, I cannot attach the full pptx file due to NDA reasons, but I think the attached 
part should help for understanding my problem.
[my_best_presentation.zip](https://github.com/singerla/pptx-automizer/files/15196480/my_best_presentation.zip)

Can you help me solve this, please?
My code is currently very simple, I just copying slides from one presentation to another, but "merge_pres" presentations can be with themeOverrides:

```typescript
import Automizer, { XmlRelationshipHelper } from './index';
import ModifyBackgroundHelper from './helper/modify-background-helper';
import { vd } from './helper/general-helper';
import ModifyImageHelper from './helper/modify-image-helper';

const run = async () => {
  const automizer = new Automizer({
    templateDir: `${__dirname}/../__tests__/pptx-templates`,
    outputDir: `${__dirname}/../__tests__/pptx-output`,
    autoImportSlideMasters: true,
    showIntegrityInfo: true,
    assertRelatedContents: true
  });

  let root_pres = automizer.loadRoot('root.pptx');
  root_pres.load('root.pptx', 'root_pres');
  root_pres.load('my_best_presentation.pptx', 'merge_pres');
  for (let i = 1; i <= 3; i++) {
    root_pres.addSlide('merge_pres', i);
    console.log('slide: ' + i);
  }
    const summary = await root_pres.write('result_auto.pptx');
    console.log(summary);
};

run().catch((error) => {
  console.error(error);
});
```

**Comment by androidsoft** [comment]
UPD:
maybe I'm wrong about themeOverride, or maybe not, because here an example with it inside and I can copy slide from pres3 to root without fail, BUT chart has default colors, not colors from themeOverride:
[pres3.pptx](https://github.com/singerla/pptx-automizer/files/15196694/pres3.pptx)

Don't know how to catch why my first pres fails on chart with themeOverride :(

**Comment by singerla** [comment]
Hi! Currently, there is no support for `themeOverride`. I think we would need a similar thing like `copyThemeFiles()` in `src/classes/master.ts`.

I need to dig deeper...

**Comment by singerla** [comment]
`themeOverride` is referenced from a chart. Please check my latest commit, I've edited `src/shapes/chart.ts`.

**Comment by androidsoft** [comment]
Hm, seems not working for me after update, same output:
```
TypeError: Cannot read properties of undefined (reading 'filenameBase')
    at Chart.<anonymous> (/Users/user/Documents/pptx-automizer-main/src/shapes/chart.ts:238:31)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/user/Documents/pptx-automizer-main/src/shapes/chart.ts:5:58)
```

I'll back here soon, need clean up sensitive stuff from my original pptx to drop here

**Comment by singerla** [comment]
I was trying to understand "my_best_presentation.zip". It seems as if `charts/_rels/chart2.xml.rels` does not contain a relation to a worksheet at all. This probably causes `TypeError: Cannot read properties of undefined (reading 'filenameBase')`.

**Comment by androidsoft** [comment]
Finally, my pptx:
[my_best_presentation.pptx](https://github.com/singerla/pptx-automizer/files/15199221/my_best_presentation.pptx)

Problems starting with copying slideLayout №5, also you can see slideLayout №6 - there is no linked xlsx for the first chart, so I can't edit it, but PowerPoint works fine with it - can we copy it "as is" to root presentation?

**Comment by singerla** [comment]
You are trying to copy slideLayouts including charts, which is supposed to be working basically. If I am trying to open the datasheet of your left-top chart `Chart Placeholder 2` on slideLayout №5, PowerPoints fails with an error message. Please try to replace the corrupted chart by a working one in your template.

**Comment by androidsoft** [comment]
Yes, you're right. And in my case I'm looking for solution to copy it as is (unfortunately), because I get presentations with templates like this massively, maybe you have ideas how to skip corrupted slideLayouts or fix them, or copy as is inside root?

**Comment by singerla** [comment]
Ok, I understand. I can remember a thing like that happened to me in the past, because PowerPoint probably lost the related worksheet on crashing. I was focusing to automate "healthy" presentations only, so I always try to repair any problem manually. 

You could surely try to modify `copyFiles()` in `src/shapes/chart.ts` and check if a worksheet relation is present first.

**Comment by androidsoft** [comment]
Thank you! I'll try that
