### ISSUE TITLE
question:  reading/writting ppt with charts

### ISSUE THREAD

**Issue by llermaly** [singerla/pptx-automizer#110]
Hello!,  congrats for this awesome library and so well maintained!. 

I'm testing the library and could not get to a clear answer about if this library can be used for what I need. 

I want to read a powerpoint with charts/tables, then programmatically replace the values of the chart/pages and save back I don't need to change any of the slides structure, just replace chart and table values. I was able to write values on an existing ppt, but not to read the current labels/values of the chart. I wonder if there is a way to read the powerpoint charts in the same format you use to modify them.

Thank you

**Comment by singerla** [comment]
Hi! Thank you so much, and I'm happy about anybody who can use this library :)

There are only a few "readers" implemented, but please take a look at https://github.com/singerla/pptx-automizer/issues/102 , there is an example about reading data from a chart.

Each modifier to set xml data can also be a reader.

I'll come back to this next week!

**Comment by singerla** [comment]
You can also take a look at https://github.com/singerla/pptx-automizer#create-a-new-modifier

It is much simpler to edit a table on a slide compared to a chart; building a table data reader should be easier.

**Comment by llermaly** [comment]
Thank you @singerla ! this is a whole new world for me. I just found that the my ppt charts are linked to Excel tables. Can I use automizer-data to manipulate those related spreadsheets? Reading the related excel tables sounds like an easier path.

**Comment by singerla** [comment]
This is for reading chart data: [read-chart-data.test.ts](https://github.com/singerla/pptx-automizer/blob/main/__tests__/read-chart-data.test.ts)
and this demonstrates on how to read table data: [read-table-data.test.ts](https://github.com/singerla/pptx-automizer/blob/main/__tests__/read-table-data.test.ts)

**Comment by llermaly** [comment]
Thanks again @singerla , You can go ahead and close this one after reading. I found some things I think its a better idea to create independent issues. 

In conclusion: 

1. There is no way to read a chart/table in the same format you use to write it. You read it as an array of arrays, you write it as an array of objects. I'm not sure if this is something that can be created as a generic parser (specially when dealing with combo charts)
2. There is a implementation to read chart data which reads the XML,  #102 will read from the underlying xls which is interesting because I found additional data like calculations in the xls which is useful for context in my use case.

**Comment by singerla** [comment]
Hi @llermaly,

regarding 1.: I'm sorry, but there is currently no function to read/write in one go. In my use cases, there is alway dummy-data in all templates. You could take a look at [automizer-data](https://github.com/singerla/automizer-data/blob/main/src/convert.ts), which I am using to prepare data objects for `pptx-automizer`. We could create a `Modelizer` with `DataPoints` from a data reader, transform and convert it.

regarding 2.: I used to remove all kinds of excel calculations from underlying xls, because you might need to manipulate a calculation chain, which is out of scope.
