### ISSUE TITLE
question: Reading/writing slide notes?

### ISSUE THREAD

**Issue by llermaly** [singerla/pptx-automizer#113]
Is there a way to read/write slideNotes ? I could'nt find anything on the documentation or Issues. 

![image](https://github.com/user-attachments/assets/03dde20e-10b3-4aa8-9b30-6131494cceda)

If there is no built in reader could you give me some directions on how to do it? 

Thanks!

**Comment by singerla** [comment]
Please take a look at [xml-template-helper.ts](https://github.com/singerla/pptx-automizer/blob/main/src/helper/xml-template-helper.ts). You can find `getSlideNameFromNotes` there which is basically used to parse slide notes. The first line will be available with:
```ts
  const creationIds = await pres.setCreationIds();
  // This will print out the first line of a slide note field
  // OR the slide title, if there is no slide note present:
  console.log(creationIds[0].slides[0].info);
```
You can also take a look at [add-slide-notes.test.ts](https://github.com/singerla/pptx-automizer/blob/main/__tests__/add-slide-notes.test.ts) to see this in action.
