### ISSUE TITLE
question: chart series colors?

### ISSUE THREAD

**Issue by jrking4** [singerla/pptx-automizer#115]
If i have a chart that is defined in the template with 4 series in, and the colors are "red", "green", "blue", and "purple" 

When replacing the chart with data that contains more than 4 series, it seems like the last series color is just repeated. is there an example or anyway to have the chart repeat the color pattern?

**Comment by MP70** [comment]
Pretty sure the only way to do this would be to set this yourself using 'style'.

**Comment by singerla** [comment]
Hi! Please check my latest commit, I've basically extended the `read` object by a simple series parser. You can now run `yarn test chart-info` to see an example.
