### ISSUE TITLE
OLE support?

### ISSUE THREAD

**Issue by mikemeerschaert** [singerla/pptx-automizer#124]
I'm trying to merge our corporate template in with a presentation I'm generating using PptxGenJS, but many of the generic slides coming in from the template contain ole objects. Once merged, the presentation throws a "needs repair" error and if you repair it, all the slides that contained ole objects in the template are blank.

I was looking through the library code and I can see that ole objects are explicitly unsupported, is there a reason for this? is this something that is very difficult to implement?

https://github.com/singerla/pptx-automizer/blob/5451192cf0d854ddb5c7fd0d2160f1dde76ac1de/src/classes/has-shapes.ts#L110-L128

**Comment by MP70** [comment]
I presume this relates to some of the more advanced charts, but if you'd be able to share an example of the pptxgenjs code and the output file I will take a look as time allows.

**Comment by mikemeerschaert** [comment]
We have a proprietary system that creates OLE charts from our database, and our users use that system to update the charts in the template from time to time. Unfortunately they are used throughout our template for ease of updating. I got permission to share a couple slides using these ole objects, so I created a minimal repo here to demonstrate the issue: 

https://github.com/mikemeerschaert/pptx-automizer-ole-sample

We have a workaround currently where we can manually convert those objects to images, but that is cumbersome and error prone, so ideally if we could have support for OLE objects, just to be added back in as they are in the original presentation, that would be awesome!

**Comment by MP70** [comment]
I have added this for you, but I still need to write a test and would be grateful for testing in general with more use cases. 

Here is your new output file, is it what you expect?
@mikemeerschaert 
[output.pptx](https://github.com/user-attachments/files/17488429/output.pptx)

To test this yourself you may grab this branch https://github.com/singerla/pptx-automizer/tree/mp70_feat_OLEsupport run npm i ; npm build then npm link - then npm link pptx-automizer in your target project. 

@singerla do you have any general opposition to my structure in that branch?

**Comment by mikemeerschaert** [comment]
I tried opening the output.pptx and I'm unable to open it. I get this series of errors. It may be because I downloaded it and it's opening in protected view, but unfortunately this is for the backend of a web app so our users will be downloading the powerpoint from the web as well.

![image](https://github.com/user-attachments/assets/0f22bd58-15ac-4c69-8827-59099aff08ce)
![image](https://github.com/user-attachments/assets/eadb1200-c3ca-49ed-bc25-3797800222ef)
![image](https://github.com/user-attachments/assets/1fbafded-ae1b-4ab6-bd6f-370edd469bdc)
![image](https://github.com/user-attachments/assets/69ee0380-35ba-4252-9df6-ad13d72432f4)

That being said, I'll play around with that branch and see what happens if I run it against the full template.

**Comment by MP70** [comment]
My apologies, I think I didn't sync my local changes. If you could do a `git fetch origin`  `git reset --hard origin/mp70_feat_OLEsupport` and try again that'd be great. But it works fine for me.

**Comment by mikemeerschaert** [comment]
Awesome, it's working now! It works fine on my test case, but interestingly when i run it against the full template, i get a "needs repair" error, however once clicking repair, the presentation works, there are no blank slides, and as far as I can tell, no missing content (although the template contains 30 fairly dense slides so I may have missed something).

Unfortunately I can't share the full template, but I'll do some work diffing the XML from the repaired presentation with the XML from the generated presentation and see if I can maybe spot the problem.

**Comment by MP70** [comment]
Great! Without seeing the full template the only immediate thought I'd have is if there's any content 'type' I've not covered here (or got wrong) https://github.com/singerla/pptx-automizer/commit/c772f4067d0a396b4caa4057b99bc08eccc355c2#diff-284913608f6db4685d8fff8009d3ead1302c669eca5d0ce2dfcccd2ce2a880f9R159

**Comment by mikemeerschaert** [comment]
I think `bin` might be missing? To be completely transparent, I really don't know much about the internal workings of PowerPoint so I'm not sure what to look for, but I did notice that this was in the repaired `[Content_Types].xml`, but not in the generated version:

```xml
<Default Extension="bin" ContentType="application/vnd.openxmlformats-officedocument.oleObject" />
```

If it helps, here is the `[Content_Types].xml` file pre and post repair. (I formatted it as it makes diffing a bit easier)

[content-types.zip](https://github.com/user-attachments/files/17499058/content-types.zip)

**Comment by MP70** [comment]
Bin is there, indeed it is in your demo file, and even in the pre-fix xml you sent `<Override PartName="/ppt/embeddings/rId6-created.bin" ContentType="application/vnd.openxmlformats-officedocument.oleObject"/>
` the fact it trips up without a default entry only on one larger file is interesting, but I think adding a default entry is lazy and not really great.

Please can you try my latest code, I'm not certain that this is the problem as I'm really stabbing in the dark without the template.

**Comment by mikemeerschaert** [comment]
I tried again and am seeing the same "needs repair" error unfortunately. I requested permission to share the full template with you privately, I'll let you know when I hear back on that. Thanks again for your time helping me with this!

**Comment by mikemeerschaert** [comment]
Ok @MP70 I got the go ahead to share the full template with you privately. I made the example repo private and added you and @singerla as collaborators. hopefully that helps diagnose where the problem is cropping up.

FWIW the template works when all the OLE objects have been manually converted to images.

**Comment by singerla** [comment]
Hi! There's a problem in e.g. `/output/ppt/slides/_rels/slide9.xml.rels`

```xml
<Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/oleObject" Target="../embeddings/rId12-created.bin"/>
<Relationship Id="rId7" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/oleObject" Target="../embeddings/rId12-created.bin"/>
```

should rather be something like
```xml
<Relationship Id="rId12-created" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/oleObject" Target="../embeddings/copy-of-oleObject3.bin"/>
<Relationship Id="rId13-created" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/oleObject" Target="../embeddings/copy-of-oleObject5.bin"/>
```

and on the slide `output/ppt/slides/slide9.xml`
```xml
<mc:Choice Requires="v">
<p:oleObj name="PEP Chartbook" r:id="rId12-created" imgW="9144000" imgH="1691640" progId="PEPChartbook.Document.1">
<p:embed/>
</p:oleObj>
</mc:Choice>
<mc:Fallback>
<p:oleObj name="PEP Chartbook" r:id="rId12-created" imgW="9144000" imgH="1691640" progId="PEPChartbook.Document.1">
<p:embed/>
<p:pic>
<p:nvPicPr>
<p:cNvPr id="8" name="Object 7"/>
<p:cNvPicPr/>
<p:nvPr/>
</p:nvPicPr>
<p:blipFill>
<a:blip r:embed="rId9-created"/>
<a:stretch>
<a:fillRect/>
</a:stretch>
</p:blipFill>
<p:spPr>
```

I'm sorry, I'm very busy this week, but I can join the OLE-party next week!

Thanks a lot for sharing and improving our library so far! It is fascinating how far you came and I'm happy to help!

**Comment by MP70** [comment]
@mikemeerschaert have sorted.

**Comment by mikemeerschaert** [comment]
Awesome, looks great, thank you!
