### ISSUE TITLE
this.archive.remove(file) not working (from archive-jszip.ts)

### ISSUE THREAD

**Issue by gjouetpastre-sephora** [singerla/pptx-automizer#128]
Hello singerla, first I would like to thank you for your amazing work, your library is very useful !

I'm currently using it to replace some images placeholders in my slides with others images dynamically computed. (using `ModifyImageHelper.setRelationTarget`). Everything is going well but when the pptx is generated the archive **still contains all the placeholders images** even if they are not used in my presentation (as all placeholders have been replaced by other images). 

It makes the output heavier than it should be.

By browsing issues on the repo I see that there are some subject about this already (and this is why we can use `cleanup: true` now).

However it is **not working for me** as the `remove` function coming from `helper/archive/archive-jszip.ts` is trying to remove `/filename` and not `ppt/media/filename`. Consequently all my unused medias are still here the final archive. I made a custom patch and now it works well:

```
diff --git a/node_modules/pptx-automizer/dist/helper/file-helper.js b/node_modules/pptx-automizer/dist/helper/file-helper.js
index fe459d8..198ba12 100644
--- a/node_modules/pptx-automizer/dist/helper/file-helper.js
+++ b/node_modules/pptx-automizer/dist/helper/file-helper.js
@@ -42,7 +42,9 @@ class FileHelper {
             const files = yield archive.folder(dir);
             for (const file of files) {
                 if (cb(file)) {
-                    yield archive.remove(file.relativePath);
+                    // Patch: send file path instead of just file name
+                    // Otherwise, file will not be found as medias are stored at ppt/media (not at the root archived)
+                    yield archive.remove(file.name);
                     removed.push(file.name);
                 }
             }
```

Either way I still have PowerPoint telling me that the file have to be repaired when I open it but I think this is the goal of these 2 todos in your code (to fix this): 

![image](https://github.com/user-attachments/assets/0743bf2e-7940-48b0-8c3b-9dcdea31f949)

Please tell me if i'm using the lib in a bad way that could explain why I have this issue and why I have to make a patch. 

Thank you very much !
Guillaume

**Comment by singerla** [comment]
Thanks a lot, Guillaume! You are completely right and I am going to commit your fix. You can run 
`yarn test  add-external-image` to see a use case.

**Comment by singerla** [comment]
Please notice: `modify-chart-scatter-images.test.ts` result pptx is broken by this fix. As this is a very rare use case, I'm going to fix this later.

**Comment by gjouetpastre-sephora** [comment]
Great ! thank you very much for your reactivity !
