### ISSUE TITLE
Disable status console output

### ISSUE THREAD

**Issue by az-nextsec** [singerla/pptx-automizer#134]
When I am using the lib to generate a file status updates such as `Appending slide` are printed to the console. How can I disable them?

**Comment by singerla** [comment]
There is currently no loglevel implemented. You could disable the `console.log` https://github.com/singerla/pptx-automizer/blob/6a0ab36f22829f0203e5672846b26da613126be2/src/helper/general-helper.ts#L22 for your purposes.

It would be great to e.g. have `logLevel` as an additional argument for `AutomizerParams`.
