### ISSUE TITLE
Clone Issue

### ISSUE THREAD

**Issue by afzal-ameri** [singerla/pptx-automizer#18]
```
$ git clone git@github.com:singerla/pptx-automizer.git
Cloning into 'pptx-automizer'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

```

**Comment by singerla** [comment]
Thank you for being interested in pptx-automizer! There are several ways to clone a repository from github. You are trying to use a SSH connection, but github does not recognize your account.
You can get additional info about [ways with git clone a repo](http://krishnaiitd.github.io/gitcommands/git-clone/) and [set up ssh keys](https://blog.realhe.ro/clone-github-repo-without-password-using-ssh/) for your machine. SSH is the most convenient way to get authenticated, but you can also use https to clone a repo:
```
git clone https://github.com/singerla/pptx-automizer.git
```
