### ISSUE TITLE
A tutorial/doc for to use this on ReactJS project?

### ISSUE THREAD

**Issue by afzal-ameri** [singerla/pptx-automizer#19]

**Comment by singerla** [comment]
Hi! I'm sorry, but pptx-generator is limited to the server side. You can't use it in a browser, as it needs to read, unzip, manipulate and zip files. Although this is also possible on the client-side, there are a lot of tradeoffs and performance problems. You would need to set up an API and use pptx-generator on a nodejs server. You might want to take a look at [prisma tools](https://www.prisma.io/), they make a great job.

You might want to prefer e.g. [gitbrent/PptxGenJS](https://github.com/gitbrent/PptxGenJS), as it provides all necessery features to create pptx on the client-side.

Please let me know if you need more information!
