### ISSUE TITLE
Depends on a vulnerable version of xmldom

### ISSUE THREAD

**Issue by victorhom19** [singerla/pptx-automizer#26]
**pptx-automizer** depends on **xmldom@^0.6.0**
**xmldom** versions 0.6.0 and older have [this vulnerability](https://github.com/advisories/GHSA-5fg8-2547-mr8q)
This can be fixed by updating to one of the fixed versions of **@xmldom/xmldom (>=0.7.0)**

**Comment by singerla** [comment]
Thank you for noticing about xmldom vulnerability. I have switched to @xmldom/xmldom 0.8.2 and also published a new version.
