### ISSUE TITLE
Adding slides at specific position

### ISSUE THREAD

**Issue by AlexanderKulia** [singerla/pptx-automizer#29]
Adding slides at specific position would be a great addition to the library. Without it someone still has to go through the presentation and reorder slides. Of course, this needs to be done only if the order is important. In my use case it is.

### Ideal final result of the merge
staticSlide1 ("root.pptx")
staticSlide2 ("root.pptx")
staticSlide3 ("root.pptx")
dynamicSlide1 (pptx-automizer)
dynamicSlide2 (pptx-automizer)
dynamicSlide3 (pptx-automizer)
staticSlide4 ("root.pptx")
staticSlide5 ("root.pptx")
staticSlide6 ("root.pptx")

**Comment by singerla** [comment]
Great idea! There might even exist a shortcut to achieve this: Take a look at ``truncate()`` in ``src/classes/template.ts``. We already have a list of existingSlides which waits to be reordered.

But, to implement this a generic way, we should first be able to apply some kind of presentation-modifier. Reorder slides could be one of those as well as modifying e.g. color schema.

**Comment by singerla** [comment]
In the meantime, you might be interested in ``removeExistingSlides``property:

``ts
const automizer = new Automizer({
  // ...
  // truncate root presentation and start with zero slides
  removeExistingSlides: true,
})
``

**Comment by AlexanderKulia** [comment]
Thanks for the suggestion. 

If I understand it correctly, first I need to add all dynamic slides using ppt.addSlide and then write those changes to XML by calling ppt.rootTemplate.appendSlide(slide).

Now the full XML structure of static and dynamic slides is available and children of `p:sldIdLst` need to be reordered.

Does this make sense or there is an easier way? I got it to work, but am facing a weird issue where some children of `p:sldIdLst` have parentNode: null.

```
async function main() {
  const ppt = automizer.loadRoot('test.pptx').load('dtest.pptx', 'dtest');
  ppt.addSlide('dtest', 1);

  // writes slides to XML and empties slides array because it's already been added to XML
  for (const slide of ppt.rootTemplate.slides) {
    await ppt.rootTemplate.appendSlide(slide);
  }
  ppt.rootTemplate.slides = [];

  // all XML nodes are available now
  const xml = await ppt.rootTemplate.getSlideIdList();
  const existingSlides = xml.getElementsByTagName('p:sldId');

  // reordering logic here

  // save the reordering
  await XmlHelper.writeXmlToArchive(
    await ppt.rootTemplate.archive,
    `ppt/presentation.xml`,
    xml
  );

  const summary = await ppt.write('reorder.pptx');
  return JSON.stringify(summary);
}
main();
```

**Comment by AlexanderKulia** [comment]
Literally seconds after writing the previous message I understood the benefit of removeExistingSlides 🤦 

1. put static and dynamic slides into one .pptx file
2. set removeExistingSlides to true
3. load this file in both loadRoot and root
4. add slides in whatever order you need

```
const ppt = automizer.loadRoot('test.pptx').load('test.pptx', 'test');

ppt.addSlide('test', 2);
ppt.addSlide('test', 4);
ppt.addSlide('test', 3); 
ppt.addSlide('test', 1);
```

**Comment by singerla** [comment]
Hi! Exactly, this is the workaround I was suggesting. You can load a root presentation, truncate it and reorder the root presentation slides by appending them in a different order.

But, the better way would be some reusable function inside "// reordering logic here" mentioned above. I was thinking about something like ``sliceCollection`` from ``xml-helper.ts``, but extendet to ``sortCollection``.

**Comment by singerla** [comment]
I've added an example to [readme](https://github.com/singerla/pptx-automizer/#how-to-sort-output-slides).

But this still needs a better solution.

**Comment by singerla** [comment]
I have attached a new branch to this issue: [feature-modify-presentation](https://github.com/singerla/pptx-automizer/tree/feature-modify-presentation).

Please check out the branch and run `yarn dev` to test it against the demo files.

Thanks a lot so far for the inspiration!

**Comment by singerla** [comment]
Your suggested code was very close to the final solution. I did not expect to have a lot of logic inside the `main()` block from your example, as this was designed only to provide a pattern for the output presentation and leave all execution to `write()`.

You will find a new array of callbacks `this.modifyPresentation` which is applied right after all append-slides-promises are resolved.

If you can confirm this to work properly, I am going to merge it into main branch.

**Comment by AlexanderKulia** [comment]
Tried a couple of combinations. It works great if all slide numbers are used in `order`. 

.sortSlides should throw an error if order.length !== slides.length. In some cases it works unexpectedly, in others PPT gets corrupted if order.length < slides.length.

```typescript
ppt.loadRoot('root.pptx').load('dynamic.pptx', 'dynamic');

ppt.addSlide('dynamic', 1);
ppt.addSlide('dynamic', 2); // total 6 slides in the root now

ppt.modify(ModifyPresentationHelper.sortSlides([4, 5, 1, 2, 6])); // notice 3 is missing. this line corrupts the file 
```

**Comment by singerla** [comment]
Thanks for pointing out. I've added a function to finally normalize the presentation, which is now limited to enumerate slide ids (starting by 256). PPT will be corrupted if slide collection is not well enumerated.

Thanks a lot for your participation! :1st_place_medal:
