### ISSUE TITLE
Add/Delete Series and Categories to Chart

### ISSUE THREAD

**Issue by LBrenac** [singerla/pptx-automizer#3]
Hello Thomas,

Thank you for the development, it's works fine !

Could you please add possibility to add and/or delete series and categories to an existing charts (and automatically recalculate data zone area) or have you already plan to do this evolution ?

Thank You
Luc

**Comment by singerla** [comment]
Hi Luc, thank you for trying pptx-automizer!

At the moment, it is only possible to add categories. Adding series will crash ppt.
Deleting series or categories is not implemented yet, but I will add this soon!

Thank you for hinting!

**Comment by LBrenac** [comment]
Thank you Thomas !

For your information, if I add a category, (e.g. I add { label: 'cat 2-5', values: [ 26, 50, 20 ] } in your sample), it crash when writing the pptx to the disk (pres.write (....) with the following message :

"TypeError: Cannot read property 'firstChild' of undefined
    at Function.setChartData (C:\Users\ppuk385\DATA\testAutomizer\node_modules\pptx-automizer\dist\helper\xml.js:203:21)
...
"

**Comment by singerla** [comment]
Hi Luc,

please update pptx-automizer to the latest version (v0.0.16)[https://github.com/singerla/pptx-automizer/releases/tag/v0.0.16]. You should be able to add categories as well as series. Please notice: new series will be derived from the previous existing one and therefore have exactly the same formatting.

This issue will stay open until deleting categories and series will be implemented.

Thank you for reporting and have a nice day!

**Comment by singerla** [comment]
Unneeded series or categories will be auto-removed by [v0.0.17](https://github.com/singerla/pptx-automizer/releases/tag/v0.0.17).

"Unneeded" means: you may have designed a chart template with a lot of series and categories as dummy data. When inserting a data object with less series or categories, the odd dummy data will be removed.

**Comment by LBrenac** [comment]
Hi Thomas,
Everything works well with this new version when adding / deleting series and/or categories
Thank you and have a nice day !
