### ISSUE TITLE
Can't use root template without any slide

### ISSUE THREAD

**Issue by maikab** [singerla/pptx-automizer#4]
As it seems, a root template must contain at least one slide to work properly.

Otherwise, an error occurs:

TypeError: Cannot read property 'appendChild' of undefined

      66 |
      67 |     const parent = element.parent(xml);
    > 68 |     parent.appendChild(newElement);
         |            ^
      69 |
      70 |     XmlHelper.writeXmlToArchive(element.archive, element.file, xml);
      71 |

      at Function.<anonymous> (src/helper/xml-helper.ts:68:12)
      at fulfilled (src/helper/xml-helper.ts:5:58)

**Comment by singerla** [comment]
Thank you for reporting this! An empty presentation is missing the parent node for a slide list.

**Comment by singerla** [comment]
Adding a new slide will now assert an existing slide list parent in presentation.xml [fixed](https://github.com/singerla/pptx-automizer/commit/27209f0d726e2717ddfe1d1bbfb8616e1fa0cef7)
