### ISSUE TITLE
Get number of slides in a presentation

### ISSUE THREAD

**Issue by cornetr** [singerla/pptx-automizer#45]
Hello, I'm searching for how to get number of slides in a presentation.
I would like to add all slides from a loaded presentation in my root presentation.
Is there any way to do it with pptx-automizer ?
I searched in different attributes of my 'pres' object (like your example) but i didn't find anything :(

Could you help me ? Thanks a lot

**Comment by singerla** [comment]
You could try this:

```ts
  // You need to load your root template twice
  const pres = automizer
    .loadRoot(`RootTemplateWithImages.pptx`)
    .load(`RootTemplateWithImages.pptx`, 'myRoot')
    .load(`SlideWithImages.pptx`, 'images');

  // setCreationIds() is used internally to map element names to corresponding pptx ids.
  const creationIds = await pres.setCreationIds();

  // You can now take a look into the structure of all loaded templates.
  console.log(creationIds);

  // filter or find a specific template in creationIds:
  // 'name' key will hold template alias (e.g. 'myRoot') or template filename
  console.log(creationIds.find((loadedTpl) => loadedTpl.name === 'myRoot'));
```

**Comment by singerla** [comment]
I guess this is quite similar to #25. I need to add this to readme :laughing:

**Comment by singerla** [comment]
Please notice: You need to use creation IDs instead of running numbers (for slides) or element names (for shapes on slides), if you have once used `pres.setCreationIds()`. Calling the function will assume you are now going to switch to creationId-mode. I'm trying to implement a switch or so...

**Comment by cornetr** [comment]
Thanks a lot for your help Thomas ! 😉

I managed to do it with your example and some modifications to fit my usage.

If it can help someone : 

```
let pres = automizer
  .loadRoot(`deb.pptx`)
  .load(`mid.pptx`, "mid")
  .load(`end.pptx`, "end");

async function merge() {
  const ids = await pres.setCreationIds();

  const midSlides = ids.find((tpl) => tpl.name === "mid").slides;
  midSlides.sort((a, b) => a.number - b.number);

  midSlides.forEach((tpl) => {
    pres.addSlide("mid", tpl.id);
  });

  const endSlides = ids.find((tpl) => tpl.name === "end").slides;
  endSlides.sort((a, b) => a.number - b.number);

  endSlides.forEach((tpl) => {
    pres.addSlide("end", tpl.id);
  });

  pres.write(`myPresentation.pptx`);
}

merge();
```
I think it could be a great idea to sort slides by `number` attribute even after `setCreationIds()` 👍

Have a good day ! ✨
