### ISSUE TITLE
Can't find *element* on slide

### ISSUE THREAD

**Issue by cornetr** [singerla/pptx-automizer#46]
Hello Thomas, I'm searching for how to replace text values in a slide.
I think i understand how it works with pptx-automizer, i have a tag in PowerPoint for my text label (named `prog`).
I can find it in my `elements` Array but i have the same error again and again :
![image](https://user-images.githubusercontent.com/90006040/214096306-08dc8275-1727-4450-ac82-380151630ef7.png)
Do you have any solution ? Thanks a lot 🙏

You can find my code here : 
```
let pres = automizer
  .loadRoot(`deb.pptx`)
  .load(`mid.pptx`, "mid")
  .load(`end.pptx`, "end");

async function merge() {
  const ids = await pres.setCreationIds();

  const midSlides = ids.find((tpl) => tpl.name === "mid").slides;
  midSlides.sort((a, b) => a.number - b.number);

  const myTplt = midSlides[0];
  console.log(myTplt.elements);
  pres.addSlide("mid", myTplt.id, (slide) => {
    slide.modifyElement("prog", (e) => {
      //do something
    });
  });

  const endSlides = ids.find((tpl) => tpl.name === "end").slides;
  endSlides.sort((a, b) => a.number - b.number);

  endSlides.forEach((tpl) => {
    pres.addSlide("end", tpl.id);
  });

  pres.write(`myPresentation.pptx`).then((summary) => {});
}

merge();
```

**Comment by singerla** [comment]
This is also related to `pres.setCreationIds()`: Once called, it will switch creationId mode for both, slides and elements. Take a closer look at your `const ids`. It will also contain an array of `ElementInfo` for each slide. You will find the required selector there, e.g.
```ts
    slide.modifyElement("{EFC74B4C-D832-409B-9CF4-73C1EFF132D8}", (e) => {
      //do something
    });
```

See an example in `__tests__` folder: `modify-by-creation-id.test.ts`

To see text replacement in action, take a look at `replace-tagged-text.test.ts` and `pptx-templates/TextReplace.pptx` according to it.

Two prevent other users from this caveat with `pres.setCreationIds()`, I need to fix this, so only `AutomizerParams.useCreationIds` should rule.

**Comment by singerla** [comment]
You can now use `pres.setCreationIds()` without the need to use creationId selectors for slides and elements. Those are only required if initialized with
```ts
const automizer = new Automizer({
    // ...
    useCreationIds: true,
  });
```

Please pull main branch to get the latest version.

**Comment by cornetr** [comment]
Thanks a lot Thomas !
I will try the lastet version 😊
