### ISSUE TITLE
Modify root Presentation & accessing other properties

### ISSUE THREAD

**Issue by LBrenac** [singerla/pptx-automizer#5]
Hi Thomas,

Thank you for the previous evolutions. It works well !

Could you please add (and illustrate) the following features:  
- Modify elements in root presentation / root presentation master
- Modify additional graph properties like activating (or not) Legend, title, X axis, ...
- Modify cell format (e.g. specify format such as @,%, 990,00, ....) or to access to other properties (e.g. set the background color of serie X) ?

I think it would be great to be able to change elements in the root Presentation, for example, for specifying dynamically  a Title, Date of report, ... (*)

Thank you Thomas for the work 
Have a nice day
Luc

(*) Actually, the only possibility to do that consists in unzipping the pptx, replacing some elements and then zipping again...

**Comment by singerla** [comment]
Thanks a lot Luc for sharing your ideas! They seem very useful to me, too.
I will seperate your thoughts into single issues:

- Modify elements in root presentation: #6 
- Modify presentation master: #7
- Modify additional graph properties: #8

**Comment by singerla** [comment]
Regarding this:
>     * Modify cell format (e.g. specify format such as @,%, 990,00, ....)

Will this be possible by linking data label format to source format in datasheet? automizer should keep the original number format from chart template. I'm not sure on this.

**Comment by LBrenac** [comment]
Hi Thomas,

Just for your information but you know that, in VBA, you can call formatNumber() to specify the format and you can specify some formats with data source, formats differents from source template (e.g. 0.35% when the template is configured with ´General' for example).
I agree with you when you say that automizer should keep the original format from chart template. 

When you link data with some formats (e.g. 0.35%), the new formats overide the default (in the template) but sometimes we want specify programmatically format such as '999.99'. If it's not correctly define in the template (e.g. forget to set correctly for one cell of a serie in a chart the good format), it doen't matter.

The main aspect for me is when you expand a chart (e.g. adding series), I'm not sure that, the format will be propagate correctly (does it inherit from previous serie ?) ...I don't think so.

Thank you Thomas and have a very nice weekend 
Luc


> automizer should keep the original number format from chart template
>

**Comment by LBrenac** [comment]
Hi Thomas,

I've found a bug. I send you this by email but if you prefer, I can open a bug on GitHub.

To reproduce it ;

Create a template with 1 categorie and 2 series (Cell are number format)
And then, send these data to the existing chart :

Final Dump : {
  series: [
    { label: 'Participants Soc1' },
    { label: 'Participants Soc2' },
    [length]: 2
  ],
  categories: [
    { label: 'Feb 2021', values: [ 3, 5, [length]: 2 ] },
    { label: 'Dec2020', values: [ 1, 2, [length]: 2 ] },
    { label: 'Jan2021', values: [ 3, 5, [length]: 2 ] },
    [length]: 3
  ]
}


When I try to write the file :

{
  modify: [Function (anonymous)],
  children: { v: { modify: [Function (anonymous)] } }
}
Error: Index 0 not found at "c"
    at ModifyXmlHelper.assertNode (/Users/luc/gentdb/node_modules/pptx-automizer/dist/helper/modify-xml-helper.js:39:23)
    at ModifyXmlHelper.modify (/Users/luc/gentdb/node_modules/pptx-automizer/dist/helper/modify-xml-helper.js:24:18)
    at ModifyXmlHelper.modify (/Users/luc/gentdb/node_modules/pptx-automizer/dist/helper/modify-xml-helper.js:31:22)
    at /Users/luc/gentdb/node_modules/pptx-automizer/dist/modify/modify-chart.js:143:27
    at Array.forEach (<anonymous>)
    at ModifyChart.setWorkbook (/Users/luc/gentdb/node_modules/pptx-automizer/dist/modify/modify-chart.js:141:30)
    at ModifyChart.modify (/Users/luc/gentdb/node_modules/pptx-automizer/dist/modify/modify-chart.js:69:14)
    at /Users/luc/gentdb/node_modules/pptx-automizer/dist/helper/modify-helper.js:49:66
    at /Users/luc/gentdb/node_modules/pptx-automizer/dist/classes/shape.js:88:41
    at Array.forEach (<anonymous>)

I hope this trace will help you Thomas.
Best regards
Luc
