### ISSUE TITLE
TypeError: slide.useSlideLayout is not a function

### ISSUE THREAD

**Issue by andrew-t-adaas** [singerla/pptx-automizer#57]
Greetings, thank you for the great tool first, I know that you just uploaded new changes, but I already have a question about them.

**pptx-automizer version:** 0.3.0 
**env:** Node v16.13.0 + TS

I want to combine several slides together into one slide deck, they have different layouts and I've seen that you've updated a version with the changes I'm looking for (hopefully). 
I've tried to use the same way as in the example: 

```
// Import a slideMaster and its slideLayouts:
pres.addMaster('SlidesWithAdditionalMaster.pptx', 1);

// It is also possible to use the original slideLayout of any added slide:
pres.addSlide('SlidesWithAdditionalMaster.pptx', 3, (slide) => {
  // To use the original master from 'SlidesWithAdditionalMaster.pptx',
  // we can skip the argument:
  slide.useSlideLayout();
  // This will also auto-import the original slideMaster, if not done already, 
  // and look for the created index of the source slideLayout.
});
```

But it seems like slide.useSlideLayout is missing in export, or I did something wrong. 

Also, the same situation with :
```
 // Always use the original slideMaster and slideLayout of any
 // imported slide:
 autoImportSlideMasters: true,
```
  
 Thanks in advance, looking forward to your reply!

**Comment by singerla** [comment]
Hi! I'm glad you like it :)

Please, try again with version 0.3.1! I needed to fix the ISlide interface in order to get rid of the messages mentioned above. Sorry for the inconvenience.

The new version also includes some methods to prevent corrupted pptx files, especially when importing e.g. images, charts or think-cell contents from slideLayouts.

It would be great if you could give feedback on any further issues with the new feature.

**Comment by singerla** [comment]
I needed to refactor slideLayouts handling to improve support of related contents. If you are having trouble with corrupted pptx files, you can try 0.3.2.

**Comment by andrew-t-adaas** [comment]
I've used the old 2007 format, and It works well with different themes. New formats work as well, even during 2-way migration from GS to local and then back.  
I've found some cases with slide resolution conversion (I've tried to combine your slides from examples and other slides and elements' positions, text sizes, etc were changed). But this is expected behavior for me. 
Didn't find any issues with importing even in v0.3.0.


In any case, I'm going to run more tests with production data very soon and will keep you updated if find something :) 
Many thanks!

**Comment by singerla** [comment]
That sounds good! Thank you for testing.

I can confirm the issues with slide resolution, but I think this doesn't need to be improved.

The recent changes to `src/enums/image-type-map.ts` will fix broken relations needed in Content_Types; in my case this has been Think-Cell related stuff. This is a good place to add more extensions in case ppt complains on opening a pptx file.

Feel free to re-open this issue if you encounter repair messages by powerpoint.
