### ISSUE TITLE
Types for setAxisRange are incorrect

### ISSUE THREAD

**Issue by thulstrup** [singerla/pptx-automizer#64]
Hi, thank you for a really great project.

I noticed that the `modify.setAxisRange` has a type error:
`Type '(chart: XmlDocument) => void' is not assignable to type 'ShapeModificationCallback'`

Changing the setAxisRange method from:
```
static setAxisRange =
  (range: ChartAxisRange) =>
    (chart: XmlDocument): void => {
```
to:
```
static setAxisRange =
  (range: ChartAxisRange) =>
    (element: XmlDocument | XmlElement, chart?: XmlDocument): void => {
```
seems to fix the error but I'm unsure if that is the correct approach.

**Comment by singerla** [comment]
please check out v0.3.5 and have a great weekend!

**Comment by thulstrup** [comment]
@singerla that was quick! Thank you so much 🙂
And a great weekend for you too.
