### ISSUE TITLE
Can't find element on slide 1 in test.pptx:

### ISSUE THREAD

**Issue by im-rasulev** [singerla/pptx-automizer#67]
Good time of day.

I'm having trouble replacing text from a presentation template. The examples given in here work out correctly (`RootTemplate.pptx`  and `TextReplace.pptx`). But as soon as I try to replace the text from my presentation (the {{test}} tag is specified on the first slide), nothing works:

 ```
slide.modifyElement(
  'replaceText',
   modify.replaceText(
   [{ replace: 'test', by: { text: 'work' } }],
   { openingTag: '{{', closingTag: '}}' }
  ))
```
As I understood from the error, the `'replaceText'` selector does not find it.
Can you tell me how to set these selectors to text objects in your presentations?

**Comment by singerla** [comment]
Hi! Please make sure that the text element on your custom slide matches the selector. Regarding the test case, `replaceText` is the name of the shape. You can display and manage shape names in PowerPoint by opening the "Selection Pane" with ALT+F10 ([see MS-docs here](https://support.microsoft.com/en-us/office/use-the-selection-pane-to-manage-objects-in-documents-a6b2fd3e-d769-46c1-9b9c-b94e04a72550). It is very likely that your shape has a different name by default, e.g. `Textfield 4` or so.

**Comment by singerla** [comment]
I have added some more details regarding this to Readme. Please take a look at [this section](https://github.com/singerla/pptx-automizer#select-slide-by-number-and-shape-by-name) to find more information on this.
