### ISSUE TITLE
How should I handle the case where the elements have the same name?

### ISSUE THREAD

**Issue by guotingchao** [singerla/pptx-automizer#68]
If the Element Name modified by ModifyElement is the same, only the last entry will be processed.

**Comment by singerla** [comment]
Hi! You can to use a selector with creationIDs to decouple a modifier from element name.

Please take a look at this example:

```ts
  const automizer = new Automizer({
    templateDir: `${__dirname}/../__tests__/pptx-templates`,
    outputDir: `${__dirname}/../__tests__/pptx-templates`,
    // Set this to `true` if you like to use creationIds by default for both, 
    // elements AND slides.
    useCreationIds: false,
  });

  const pres = automizer
    .loadRoot(`RootTemplate.pptx`)
    .load(`SlideWithShapes.pptx`, 'shapes');

  // you can read some information about your templates.
  const creationIds = await pres.setCreationIds();
  console.log(
    creationIds
      .find((template) => template.name === 'shapes')
      .slides.find((slide) => slide.number === 2),
  );
  
  // We are still using slide numbers to find the target slide.
  // CreationID for this slide would be 273148976.
  await pres
    .addSlide('images', 1, (slide) => {
      // You can use both, creationId as primary selector and
      // name as fallback:
      slide.addElement('shapes', 2, {
        creationId: '{E43D12C3-AD5A-4317-BC00-FDED287C0BE8}',
        name: 'Drum',
      } as FindElementSelector);
    })
    .write(`modify-shapes.test.pptx`);
```

Please not: When turning on `useCreationIds: true`, you need to find out each creationId for both, all slides and all shapes. The may appear more complicated on first sight, but, you don't need to care about slide sortation and element names when your templates are evolving.

**Comment by guotingchao** [comment]
@singerla  Thanks for your reply, but I was expecting to make content changes on a PPT template that was already styled, not just add elements, so maybe I didn't quite get the point.
```
 slide.addElement('shapes', 2, {
        creationId: '{E43D12C3-AD5A-4317-BC00-FDED287C0BE8}',
        name: 'Drum',
      } as FindElementSelector);
  })
```
**Here it looks as if the addition was done directly and the name set**

**Comment by singerla** [comment]
I have added some more details regarding this to Readme. Please take a look at [this section](https://github.com/singerla/pptx-automizer#select-slide-by-number-and-shape-by-name) to find more information.

Please let me know if this is helpful to you or if you need e.g. more examples on this.

Thanks in advance for your participation :smiley:

**Comment by guotingchao** [comment]
Thanks for the guide, I solved the problem
