### ISSUE TITLE
Questions about template application

### ISSUE THREAD

**Issue by guotingchao** [singerla/pptx-automizer#69]
I have a file as a master RootTemplate, using an already edited file as Test, but I find that the template setting doesn't take effect, either using addMaster or addSlide just adds a new page with the specified PPTX!

**Comment by guotingchao** [comment]
```ts
const { join } = require("path");
const { Automizer, ModifyTextHelper } = require("pptx-automizer");

const generatorPowerPoint = async () => {
  const templatePath = join(process.cwd(), "/template");
  const outputPath = join(process.cwd(), "/output");
  const automizer = new Automizer({
    templateDir: templatePath,
    outputDir: outputPath,
    autoImportSlideMasters: true,
    removeExistingSlides: true,
  });
  automizer
    .loadRoot("Template-01.pptx")
    .load("Template-01.pptx", "master")
    .load("RootTemplate.pptx", "template");

  automizer.addSlide("template", 1, (slide) => slide.useSlideLayout());
  automizer.addMaster("master", 1);

  automizer.write(`test.pptx`);
};
```

**Comment by guotingchao** [comment]
RootTemplate.pptx and Template-01.pptx I've tried swapping use loadRoot and load

**Comment by singerla** [comment]
Hi! I am trying to reproduce this with templates from `__tests__/pptx-templates` directory of this repository. I was using a copy of `SlidesWithAdditionalMaster.pptx` as `Template-01.pptx`. It works as expected in all combinations...

If set to `true`, `autoImportSlideMasters` will make `addMaster` and `useSlideLayout` obsolete:
```ts
  // slide.useSlideLayout() is already executed by functionality behind autoImportSlideMasters
  automizer.addSlide("template", 1, (slide) => slide.useSlideLayout());

  // this will import first master & associated layouts from "Template-01.pptx"
  // again, so this makes a copy of a slideMaster within the root template.
  automizer.addMaster("master", 1);
```
Please notice: You won't need any slideMaster magic in case that all of your templates are using the same set of masters. If those are equal, you are not going to notice any difference in slide mode anyway :)

Please open slide master view in PowerPoint (as described e.g. [here](https://thepowerpointblog.com/quick-access-to-slide-master/)) and check if there are more slide masters and slide layouts as in original root template.

You could try this: 
```ts
  automizer
    .loadRoot('RootTemplate.pptx')
    .load('RootTemplate.pptx', 'template')
    .load('SlidesWithAdditionalMaster.pptx', 'master');

  // will duplicate slideMaster #1 of 'RootTemplate.pptx'
  automizer.addSlide('template', 1);
  // will add slideMaster #2 of 'SlidesWithAdditionalMaster.pptx':
  automizer.addSlide('master', 1);

  await automizer.write(`test.pptx`);
```
This will output a three-master-presentation from our __tests__-files.

Happy mastering! :)

**Comment by guotingchao** [comment]
@singerla  Thanks, this issue was caused by my biased understanding of the template and can be closed now.
