### ISSUE TITLE
Functionality Question

### ISSUE THREAD

**Issue by chriscap-fd** [singerla/pptx-automizer#71]
Thanks for putting this library together.  I'm trying to do something fairly simple.  I have an PPT template that I want to do some search/replace with tokenized strings.  IE - {{NAME}} replace with a name.  I see that I can do that when I add a slide, but I can't see how I do that with existing slides.  When I load a PPT into automizer, it doesn't actually show the slides.  But when I save it, the slides are there.  I must be missing something.  Ideally, I'd love to loop through each slide and perform modifications, but I just can't find a way to do this.

**Comment by singerla** [comment]
Hi! I've added a [new example to readme](https://github.com/singerla/pptx-automizer#loop-through-an-existing-presentation). You will find some suggestions on how to loop through each slide of a loaded presentation.

For more details about text replacements, you might already have found [the test](https://github.com/singerla/pptx-automizer/blob/main/__tests__/replace-tagged-text.test.ts). 

In combination with the example from readme, this should do the job:

```ts
const callbacks: CallbackBySlideNumber[] = [
  {
    slideNumber: 2,
    callback: (slide: ISlide) => {
      slide.modifyElement(
        'replaceText',
        modify.replaceText([
          {
            replace: 'Bananas',
            by: {
              text: 'Apples',
            },
          },
        ]),
      );
    },
  },
];
```

Have fun with `pptx-automizer` :smiley: and don't hesitate to share your experience.

**Comment by singerla** [comment]
Oh, I forgot to mention: you need the latest version 0.4.1. Please find a working example in `dev.ts`.

**Comment by MP70** [comment]
@singerla this is very cool! Is this any more efficient than using the old 'getAllSlideNumbers' implementation I wrote?

```
const slideNumbers = await pres
          .getTemplate(section.id)
          .getAllSlideNumbers()

 for (const slideNumber of slideNumbers) {
//do the thing
}
```
@chriscap-fd , I also wrote this helper `const elementIds = await slide.getAllTextElementIds();` which you may find useful together with either method above for doing this. If you need a help shout up, I've done this a few times.

**Comment by chriscap-fd** [comment]
This is all awesome and super helpful.  I think I have something basic going now!  @MP70 thanks also for your tip.  Very helpful.

**Comment by chriscap-fd** [comment]
As I'm getting through this, I'm noticing the Slides that come back from getInfo() are not the same that you get in the callback.  Is there a way to unify this?  If I want to loop through all elements on a slide, I need getInfo() slides.  Elements don't hang of the ISlide that's in the callback.  That would be very useful.

**Comment by singerla** [comment]
@chriscap-fd: At the moment, `getInfo()` is a tiny wrapper around `setCreationIds()` and will return the state of all templates after loading. It is not connected to `ISlide` and will not be updated during runtime, while `slide.getAllTextElementIds()` parses the *current* slide content. I agree, `ISlide` should contain some more tools.

@MP70: If you run `getInfo()`, it will parse each element on each slide in each presentation. If you know what you need to count, `XmlTemplateHelper.getAllSlideNumbers` will be much faster. Needs to be added to readme :smiley: 

Thank you so much for sharing your experience! :smiley:
