### ISSUE TITLE
Tip: How To Loop Through Slides and/or Programatically Replace Text

### ISSUE THREAD

**Issue by vertex-admin** [singerla/pptx-automizer#72]
It took me hours to figure this out so thought I'd share a quick workaround on how to:
i) loop through all the slides in a presentation
ii) replace all instances of the text you want to replace, without needed to know/hardcode the selector names

This won't work for text in tables though, if anyone has a tip on how to do that, I'd be happy to try.
```js
   let variableData = [{variable: "First Name", value: "John"}, {variable: "Last Name", value: "Doe"}]
   let textReplacements = [];
   let templateName = 'test';

    variableData.forEach(async variable => {
        textReplacements.push({
            replace: variable.variable,
            by: {
                text: variable.value,
            },
        });
    });
    
    // Load Pptx Automizer
    const automizer = new Automizer({
        templateDir: templateDir,
        outputDir: outputDir,
        removeExistingSlides: true,
    });

    let pres = automizer.loadRoot(rootTemplate).load(extraTemplate, templateName);

    // Count the total number of slides
    const creationIds = await pres.setCreationIds();
    let totalSlides = 0;

    creationIds.forEach((template) => {
        totalSlides += template.slides.length;
    });

    console.log(`Processing ${totalSlides} slides!`);
        
    // Loop through all the slides
    for (let i = 1; i <= totalSlides; i++) {
        pres.addSlide(templateName, i, async slide => {
            let placeholders = await slide.getAllTextElementIds();    

            // Replace text for each placeholder programatically
            placeholders.forEach(async placeholder => {
                slide.modifyElement(
                    placeholder,
                    modify.replaceText(textReplacements),
                );
            });
        });
    }

    // Write the output file
    pres.write('Output.pptx').then((summary) => {
        console.log(summary);
    });
```

**Comment by singerla** [comment]
Great! Thanks a lot for sharing! :smiley: 

You can make use of the new `pres.getInfo()` that came yesterday with `v0.4.1` to make the code even shorter:

```ts
    // ...

    let pres = automizer.loadRoot(rootTemplate).load(extraTemplate, templateName);

    // getInfo() is a tiny wrapper around setCreationIds():
    const presInfo = await pres.getInfo();
    // Count the total number of slides
    const totalSlides = presInfo.slidesByTemplate(templateName).length;

    console.log(`Processing ${totalSlides} slides!`);
        
    // Loop through all the slides
    // ...
```

Best regards and keep on sharing!

**Comment by Suniron** [comment]
How to deal with only one template (the root template)?

**Comment by b1ues** [comment]
I found a strange problem where some fields cannot be replaced, such as: installedCapacity. Can someone help me try it out?

**Comment by b1ues** [comment]
> I found a strange problem where some fields cannot be replaced, such as: installedCapacity. Can someone help me try it out?

I found a strange problem where some fields cannot be replaced, such as: installedCapacity. Can someone help me try it out?

**Comment by b1ues** [comment]
> It took me hours to figure this out so thought I'd share a quick workaround on how to: i) loop through all the slides in a presentation ii) replace all instances of the text you want to replace, without needed to know/hardcode the selector names
> 
> This won't work for text in tables though, if anyone has a tip on how to do that, I'd be happy to try.
> 
> ```js
>    let variableData = [{variable: "First Name", value: "John"}, {variable: "Last Name", value: "Doe"}]
>    let textReplacements = [];
>    let templateName = 'test';
> 
>     variableData.forEach(async variable => {
>         textReplacements.push({
>             replace: variable.variable,
>             by: {
>                 text: variable.value,
>             },
>         });
>     });
>     
>     // Load Pptx Automizer
>     const automizer = new Automizer({
>         templateDir: templateDir,
>         outputDir: outputDir,
>         removeExistingSlides: true,
>     });
> 
>     let pres = automizer.loadRoot(rootTemplate).load(extraTemplate, templateName);
> 
>     // Count the total number of slides
>     const creationIds = await pres.setCreationIds();
>     let totalSlides = 0;
> 
>     creationIds.forEach((template) => {
>         totalSlides += template.slides.length;
>     });
> 
>     console.log(`Processing ${totalSlides} slides!`);
>         
>     // Loop through all the slides
>     for (let i = 1; i <= totalSlides; i++) {
>         pres.addSlide(templateName, i, async slide => {
>             let placeholders = await slide.getAllTextElementIds();    
> 
>             // Replace text for each placeholder programatically
>             placeholders.forEach(async placeholder => {
>                 slide.modifyElement(
>                     placeholder,
>                     modify.replaceText(textReplacements),
>                 );
>             });
>         });
>     }
> 
>     // Write the output file
>     pres.write('Output.pptx').then((summary) => {
>         console.log(summary);
>     });
> ```

I found a strange problem where some fields cannot be replaced, such as: installedCapacity. Can someone help me try it out?

**Comment by singerla** [comment]
Did you try to disable spell checking for the template field?

**Comment by HarshalSangme** [comment]
@singerla I'm working on a task which replaces the text present in the pptx of a particular slide. Also all functionality has been implemented in python using python-pptx lib. But I'm struggle at replacing text present in SmartArt, Charts etc. Does this pptx-automizer supports modifying SmartArt, Charts etc?

**Comment by singerla** [comment]
@b1ues Did disabling spell check solve your problem? Feel free to continue on #82 otherwise.
