### ISSUE TITLE
modify.replaceText not working properly

### ISSUE THREAD

**Issue by singerla** [singerla/pptx-automizer#73]
Aside from that, I'm having a weird issue where modify isn't working.  I think this should work, but the modify() doesn't actually replace the text.  

    let pres = automizer.loadRoot("review-template.pptx");
    pres.load("review-template.pptx", "base");
    const templates = await pres.getInfo();
    const slides = templates.slidesByTemplate("base");

    slides.forEach((slide) => {
        pres.addSlide("base", slide.number, async(slide) => {
            const elements = await slide.getAllTextElementIds();

            elements.forEach(element => {

                slide.modifyElement(element, () => {
                    modify.replaceText([
                        {
                            replace: 'NAME',
                            by: {
                                text: client.displayName
                            }
                        }]
                    )
                })
            })
        });
    });

    await pres.write("myPresentation.pptx").then((summary) => {
        console.log(summary);
    });

_Originally posted by @chriscap-fd in https://github.com/singerla/pptx-automizer/issues/71#issuecomment-1773464140_

**Comment by singerla** [comment]
I remember some weird issues in the past which could be related to this. PowerPoint's way to store text in xml can be surprisingly complex. Depending on the order of typing letters into a textbox, they eventually might split up in the file:
  
```xml
<a:t>{{NAME}</a:t>
```

```xml
<a:t>}</a:t>
```

Although I was trying to handle this by `TextReplaceHelper.isolateTaggedNodes()`, it seems not to work in all cases.

You can try a workaround: 
- Cut out your `{{NAME}}` tag from textbox to clipboard.
- Paste it into a plaintext editor (e.g. notepad) to remove all (visible and invisible) formatting.
- Copy & paste the tag back to the textbox.

This will not make any visible difference, but join the xml elements.

In general, it seems as if varying text format inside a textbox can break `modify.replaceText`.

Good luck on this!

**Comment by chriscap-fd** [comment]
Well, that was not the issue.  I'm a bit confused to be honest.  This code works.  There's a slight difference on the slide.modifyElement line.  I thought modifyElement() took a callback, so I used arrow syntax.  I looked closely at the samples, and they don't use that approach.  I replaced with just a function call and it worked.  Don't quite understand it.

    let pres = automizer.loadRoot("review-template.pptx");
    pres.load("review-template.pptx", "base");
    const templates = await pres.getInfo();
    const slides = templates.slidesByTemplate("base");


    slides.forEach((slide) => {
        pres.addSlide("base", slide.number, async(slide) => {
            const elements = await slide.getAllTextElementIds();

            elements.forEach(element => {

                slide.modifyElement(element,
                    modify.replaceText([
                        {
                            replace: 'NAME',
                            by: {
                                text: client.displayName
                            }
                        }]
                    )
                )
            })
        });
    });

**Comment by singerla** [comment]
Maybe it will become clearer if we take a look at `modify.replaceText`. I have edited the original code to emphasize where the required callback is constructed:

```ts
  /**
   * Replace tagged text content within modified shape
   */
  static replaceText = (
    replaceText: ReplaceText | ReplaceText[],
    options?: ReplaceTextOptions,
  ): ShapeModificationCallback => {
    const shapeModCallback = (element: XmlElement): void => {
      const replaceTexts = GeneralHelper.arrayify(replaceText);

      new TextReplaceHelper(options, element as XmlElement)
        .isolateTaggedNodes()
        .applyReplacements(replaceTexts);
    };
    
    return shapeModCallback;
  };
```

Applied to your code, we could add a few lines to increase readability:

```ts
const replaceParams = [{
    replace: 'NAME',
    by: {
        text: client.displayName
    }
}]

slides.forEach((slide) => {
    pres.addSlide("base", slide.number, async(slide) => {
        const elements = await slide.getAllTextElementIds();
        const shapeModCb = modify.replaceText(replaceParams) as ShapeModificationCallback;

        elements.forEach(element => {
            slide.modifyElement(element, shapeModCb);
            // which equals
            // slide.modifyElement(element, [ shapeModCb ]);
        })
    });
});
```

For convenience, you can use a single Callback or an array of callbacks. You could also use multiple calls of `slide.modifyElement()` instead of an array of callbacks, the result will always be the same.

Later on, your callback(s) will be applied to the element XML:
```ts
// taken from src/classes/shape.ts
  applyCallbacks(
    callbacks: ShapeModificationCallback[],
    element: XmlElement,
    relation?: XmlElement,
  ): void {
    callbacks.forEach((callback) => {
      if (typeof callback === 'function') {
        try {
          callback(element, relation);
        } catch (e) {
          console.warn(e);
        }
      }
    });
  }
```

If I have to handle complex code constructions like the above, it helps to add a few lines and declare a some more `const`. You have more longer, but it is easier to understand.

The latest version `v0.4.3` will contain a small type refactoring that differs `ShapeModificationCallback` and `ChartModificationCallback`.

I hope this helps! :smiley:
