### ISSUE TITLE
0.39 > 0.41 

### ISSUE THREAD

**Issue by MP70** [singerla/pptx-automizer#74]
Hi,

I was just upgrading from .39>.41 and noticed this syntax is now invalid;
`   slide.modifyElement(
                    elementId,
                    modify.replaceText(replacements, {
                      openingTag: "{",
                      closingTag: "}",
                    })
                  );
                }
              });`

and we now must 
`slide.modifyElement(
                      elementId,
                      () => {
                        return modify.replaceText(replacements, {
                          openingTag: "{",
                          closingTag: "}",
                        });
                      }
                    );
`. Is this right and should we update docs to reflect it?

**Comment by singerla** [comment]
Hi! I'm sorry for the inconvenience. This was caused by a falsy cleanup of `ShapeModificationCallback` signature.

I needed to try the 0.4.1 in VS Code, because Webstorm didn't complain. :thinking:

**Comment by singerla** [comment]
Please try 0.4.2

**Comment by MP70** [comment]
Thanks! Will do that and sync back later, for now I just did the above workaround.

**Comment by MP70** [comment]
Jumped straight to 0.44; fix looks great. Thanks, so much for this!
Closes #74
