### ISSUE TITLE
'Could not find file ppt/slides/slide{x}.xml'

### ISSUE THREAD

**Issue by MP70** [singerla/pptx-automizer#75]
Hi,

I'm also noticing an issue with I think maybe cleanup, on making two different sets of files, if the first file has 5 slides from input files A,B,C , then I run the code again on input files D,E,C and this has 4 slides I get 
`STARTING PRESWRTE
Appending slide 2 (33%)
Appending slide 3 (67%)
Appending slide 4 (100%)
Error detail: Could not find file
Stack trace: Error: Could not find file
at ArchiveJszip.<anonymous> (/node_modules/pptx-automizer/dist/helper/archive/archive-jszip.js)
at Generator.next (<anonymous>)
at /node_modules/pptx-automizer/dist/helper/archive/archive-jszip.js
at new Promise (<anonymous>)
at __awaiter (/node_modules/pptx-automizer/dist/helper/archive/archive-jszip.js)
at ArchiveJszip.read (/node_modules/pptx-automizer/dist/helper/archive/archive-jszip.js)
at ArchiveJszip.<anonymous> (/node_modules/pptx-automizer/dist/helper/archive/archive-jszip.js)
at Generator.next (<anonymous>)
at /node_modules/pptx-automizer/dist/helper/archive/archive-jszip.js
at new Promise (<anonymous>)
`
I am using all cleanup functions available, and at the end removing both input and output pptxs from /tmp where we save them for processing, and setting the autonomiser and pres instances to null; any ideas would be massively appreciated.

**Comment by singerla** [comment]
Do you think this is related to new version? It is hard to reproduce, could you please provide some more code?

Thanks in advance!

**Comment by MP70** [comment]
This removes a massive amount of complexity in my actual implementation and even some of the cleanup steps I take but try this ;

https://github.com/MP70/pptx-automizer/commit/178a02331c0a553756a0350d3f8a5e940ea434ba 

'Could not find file ppt/slides/slide9.xml'

**Comment by singerla** [comment]
Please use `v0.4.4`, some changes didn't make it to 0.4.3

**Comment by MP70** [comment]
Thanks for the tip, tested again using 0.44; fix looks great - cleanup appears to be working fine now. Thanks, so much for this!
