### ISSUE TITLE
All animations are removed whenever an element is removed

### ISSUE THREAD

**Issue by ljcsilvert** [singerla/pptx-automizer#78]
Hello,

I've noticed that whenever I want to remove an element that has an animation on it, Powerpoint makes me repair the pptx and remove all of the animations in the slide.
Do I do something wrong here? Is there already a workaround for this issue?
Otherwise, would it be possible to reorganize the animations while removing the element?

I have this issue with this code for example:
``` ts
const title = (pres: Automizer, title?: string, subtitle?: string) => {
  pres.addSlide('title.pptx', 1, (slide) => {
    if (title)
      slide.modifyElement('title', [
        modify.replaceText([{ replace: 'title', by: { title } }]),
      ])
    if (subtitle)
      slide.modifyElement('subtitle', [
        modify.replaceText([{ replace: 'subtitle', by: { subtitle } }]),
      ])

    if (!title) slide.removeElement('title')
    if (!subtitle) slide.removeElement('subtitle')
  })
}
```

My temporary solution would be to have a slightly different template for each time I have to remove an element, but it's not handy nor maintainable.

**Comment by singerla** [comment]
Hi! I'm sorry, animations are not yet supported. I'll take a look!

**Comment by singerla** [comment]
Huh, that's complicated...

There is `<p:timing>` and `<p:bldLst>` that needs to get in sync with `removeElement`... The latter is nested deeply and I have no idea how this will look when there are lots of animations on a slide.

What about `slide.hideElement`? This function does not exist yet, but I could imagine there is only `hidden` that needs to be update:
```xml
<p:sp>
  <p:nvSpPr>
    <p:cNvPr id="11" name="Drum" hidden="1">
      <a:extLst>
        ///
```

What do yo think? This will be the same effect as `ALT+F10` and toggle the eye-symbol right besides a shape.

**Comment by ljcsilvert** [comment]
I thought about that but I didn't saw the function in the documentation but yes it would work that would be great :)
Do you think it would be possible to implement the function soon? :)

**Comment by singerla** [comment]
This should do the job:

```ts
  pres.addSlide('animations', 1, (slide) => {
    slide.modifyElement('Drum', (shape) => {
      // You need to update the 'hidden' attribute with a callback: 
      shape.getElementsByTagName('p:cNvPr').item(0).setAttribute('hidden', '1');
      // XmlHelper.dump(shape);
    });
  });
```

Feel free to create a helper & PR from this! :smile:

**Comment by singerla** [comment]
I'm happy to help :smile:
