### ISSUE TITLE
Pres/Slide Dimensions

### ISSUE THREAD

**Issue by MP70** [singerla/pptx-automizer#81]
Hi, 

Hope, you're well. I was thinking of adding a method to get dimensions of a slide, right now I've popped it on the slide.getDimensions() but maybe this can go inside getInfo().slidenumber > .info eventually?

Would you like it in your lib?

If yes:
Does this feel like the right order of precedence for what dimensions override each-other? My memory says yes but I'd need to read the spec to confirm.
What do you want to see in a PR? Is this fine (with tidy up obviously, and initing the source archive in the function) more or less as is or?

https://github.com/MP70/pptx-automizer/commit/d0e028c3d486376885e399b648a4c0ca6aea64a8

**Comment by singerla** [comment]
Hi Matt,

that looks great, thank you very much! I was having issues with slide dimensions too in the past, so this is very welcome.
I was playing around with your code and moved it to `src/helper/xml-slide-helper.ts`. It can reuse some things from there (e.g. `slideXml`) and some code could be reused later, too (e.g. get related master and layout).

Have a great week! :)

Thomas

**Comment by singerla** [comment]
And feel free to add modifications directly to this repository in the future :smiley:
I have created a new branch for this feature.

**Comment by MP70** [comment]
Hi Thomas,

That is the obvious home for it, thanks! Sorry, I was just focusing on getting it working first :)

I'll get this branch into a more mergable state when I have a moment, thanks for access.

 It's a super useful feature in my eyes as it means we can layout things on the slide, (e.g center an element) as well as enabling some hygiene features such as detecting elements that are outside of the canvas, glad you're happy to include it.

**Comment by MP70** [comment]
Hi Thomas,
 
I'm just refreshing myself on this one. I think that in practice 99.9% of the time the only thing that **practically** matters is the dimensions at the template level, rather than side level. Although the pptx spec supports different slide sizes in the same file _in practice_ the major presentation packages, generally, do not, including powerpoint. 

So, I'm a bit torn on if we should just put a simpler version in at the template level e.g 
```ts
 let template = pres.getTemplate('output')
 template.getDimensions()
``` 
and cut out the complexity, or leave it at the slide level (or do both).

Whats your view?

**Comment by singerla** [comment]
Hi Matt, 

I was already wondering how to set different dimensions, and I completely agree that we can cut out complexity here. See also [MS docs](https://support.microsoft.com/en-us/office/change-the-size-of-your-slides-040a811c-be43-40b9-8d04-0de5ed79987e).

Thanks a lot again for your contribution! :smiley:
