### ISSUE TITLE
[Question] Getting element's text.

### ISSUE THREAD

**Issue by dloaizarico** [singerla/pptx-automizer#83]
Hi.

First of all, thanks a lot for the library, I think it's really good.

I wonder if you guys know a way of getting the current text of an element?

For example:

This is a callback fnt for editing existing slides:

`  const updateSlide = async (slide) => {
    const elements = await slide.getAllTextElementIds();
    elements.forEach((element, index) => {
      console.log(index);
      if (index === 4) {
        slide.modifyElement(element, [ModifyTextHelper.setText("My content")]);
      }
    });
  };`

I need to get the element text and compare if it's equal to something, I will need to update that text, at the moment, I am only able to edit existing elements but I can't find a way to validate which of the elements in the slide is the one that I need to update.

Unfortunately, I cannot use replace because my original files do not have the {{}}

Thanks a lot.

**Comment by MP70** [comment]
You can do this, although won't if the "find" text is spread across elements. Best to edit your pres to include a tag if possible 
```ts
        await slide.modifyElement(
          elementId,
          modify.replaceText(replacements, {
            openingTag: "",
            closingTag: "",
          }),```

Otherwise you'll need to do it manually like ```
      const textElements = element.getElementsByTagName('a:r');
```
etc.

**Comment by MP70** [comment]
Sorry! Yes, I modify styling in mine too - I didn't rob enough lines to show text only. Incase it's useful;
```js
      const textElements = element.getElementsByTagName('a:r');
      Array.from(textElements).forEach(textElement => {
        const textContentElements = textElement.getElementsByTagName('a:t');
        const attrsElements = textElement.getElementsByTagName('a:rPr');
```
