### ISSUE TITLE
Modify slide backgrounds

### ISSUE THREAD

**Issue by singerla** [singerla/pptx-automizer#86]
There should be a modifier for slide backgrounds. #85

**Comment by singerla** [comment]
@MP70: Could you please provide a test case to this branch and probably some example code with your required parameters?

I would like to write some docs on how to create a new modifier. :)

**Comment by MP70** [comment]
Have added a little test. It's only a indicator, there may be a neater way to arrange it, like making the background another type like shape, table etc.

**Comment by MP70** [comment]
Currently manually getting the <p:bg> / <p:bgPr> element, then modify like:

bg
  .getElementsByTagName('a:solidFill')[0]
  .getElementsByTagName('a:schemeClr')[0]
  .setAttribute('val', 'accent6');  // Change 'accent6' to your desired color value

**Comment by singerla** [comment]
Hi @MP70, please check out `modify-master-background-color.test.ts` to see a basic example.

**Comment by singerla** [comment]
@MP70: It would be great if you could also test `modify-master-background-image.test.ts` with your real world stuff. It turned that it required a slightly different approach for background images than for "normal" image elements on a slide.

@creedmangrum: This might be useful for you, too.

I'm happy about feedback on this!
