### ISSUE TITLE
Not all text replaced: modify.replaceText 

### ISSUE THREAD

**Issue by fedyunin** [singerla/pptx-automizer#89]
Hello! 

I faced with issue with replace text. Little stuck with this issue and no have idea what can be wrong.
I prepared my pptx by using Office365 Web version.

I generate pptx from template. Need replace text variables in template (e.g: {{variable}}).
In some cases variables not replaced by value.

Here my code:

```
import { Automizer, modify } from 'pptx-automizer';

const automizer = new Automizer({
    templateDir: `my/pptx/templates`,
    outputDir: `my/pptx/output`,
    removeExistingSlides: true,
});

const template = "template_test.pptx";


const pres = automizer
    .loadRoot(template)
    .load(template)

const variables = {
    'value1': 'VALUE1',
    'value2': 'VALUE2',
    'ValuE3': 'VALUE3',
    'vALUe4': 'Value4',
    'longValueName5': 'VALUE5',
    'nameOfVariable': 'Name of Variable Value',
    'starName': 'Star Name Value'
}

const textReplacements = Object.entries(variables).map(([replace, text]) => (
    {
        replace,
        by: {
            text,
        }
    }
));

const presInfo = await pres.getInfo();
const totalSlides = presInfo.slidesByTemplate(template).length;

for (let i = 1; i <= totalSlides; i++) {
    pres.addSlide(template, i, async (slide) => {
        // Use the getAllTextElementIds method to get all text element IDs in the slide
        const elementIds = await slide.getAllTextElementIds();
        elementIds.forEach(elementId => {
            slide.modifyElement(
                elementId,
                modify.replaceText(textReplacements),
            );
        });
    });
}

await pres.write(`result.pptx`);
```

For example my template has shape - Star and text variable for replace inside it. This variable not replaced.

[empty.pptx](https://github.com/singerla/pptx-automizer/files/14441728/empty.pptx)
[template_test.pptx](https://github.com/singerla/pptx-automizer/files/14441730/template_test.pptx)

**Comment by singerla** [comment]
Hi! Thank you for reporting this. I went into your pptx template xml at `/ppt/slides/slide1.xml`:

While
```xml
<a:p>
  <a:r>
    <a:rPr lang="en-US" dirty="0"/>
    <a:t>Test replace text: {{value1}} Another test: {{value2}} and one more: {{ValuE3}}</a:t>
  </a:r>
</a:p>
```
seems to work,

```xml
<a:p>
  <a:pPr algn="ctr"/>
  <a:r>
    <a:rPr lang="en-US" dirty="0"/>
      <a:t>{{</a:t>
    </a:r>
    <a:r>
      <a:rPr lang="en-US" dirty="0" err="1"/>
      <a:t>nameOfVariable</a:t>
      </a:r>
    <a:r>
      <a:rPr lang="en-US" dirty="0"/>
      <a:t>}}</a:t>
  </a:r>
</a:p>
```
is split into several `<a:rPr>` nodes.

Please refer to 
[this](https://github.com/singerla/pptx-automizer?tab=readme-ov-file#troubleshooting), #82 and #73.

**Comment by fedyunin** [comment]
Thanks for reference to other issues. 
Now understand issue. Yeah - it described in your docs. 
I thought so this issue can be appeared when used some formatting.
