### ISSUE TITLE
Copy slide master related background images on autoImportSlideMaster doesn't work

### ISSUE THREAD

**Issue by singerla** [singerla/pptx-automizer#91]
Related background images are not copied properly if `autoImportSlideMaster` is set to true. @creedmangrum: It would be great if you could provide some test pptx with you template setting to the new branch `fix-slide-master-background-image`.

**Comment by singerla** [comment]
Hi @creedmangrum, 

could you please this branch against your templates? Background images should be included now.

Cheers!

**Comment by creedmangrum** [comment]
@singerla I was on vacation for the weekend, and have a busy work week ahead, but I imagine getting to this this week to check it. Thank you!

**Comment by singerla** [comment]
Hi! Please let me know if you find any issues with it. You can use pptx-automizer (0.4.8) for this!
